# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

RUN npm run build

# Starting our application
CMD [ "npm", "run", "start" ]
